version: "3"

services:
  app:
    build: .
    ports:
     - "10.71.34.101:80:80"
     - "9229:9229"
    env_file:
      - ./config/hostlab.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
  mongo:
    image: "mongo:latest"
  ldap:
    image: "osixia/openldap:1.1.11"
    environment:
      - LDAP_DOMAIN=hostlab.local
      - LDAP_ADMIN_PASSWORD=12345
    volumes:
      - ./ldapseed.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/testuser.ldif:ro
    command: [--copy-service, --loglevel, debug]
  gitlab:
    image: "gitlab/gitlab-ce"
    hostname: gitlab
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - ./config/gitlab.rb:/etc/gitlab/gitlab.rb
    ports:
      - "9080:80"
      - "9443:443"
      - "9022:22"
